### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-jezus#25]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by tanmeshbhokare** [comment]
![image](https://user-images.githubusercontent.com/42235943/183294597-3a45c4ae-08a2-4bb4-be4f-02cf678cd36f.png)

Added placeholder.png for items without any image

**Comment by tanmeshbhokare** [comment]
updated code to add placeholder.png if image value is null.

re-tested the feature manually and it is working as expected.
